### ISSUE TITLE
关于FloatingActionButton 的点击事件的疑问

### ISSUE THREAD

**Issue by xiechuanyu** [zyascend/RecompileToDo#1]
你好，为什么我删掉了TasksFragment 中112行到121行（即FloatingActionButton 的点击事件的监听代码），为什么点击后仍然可以跳转到AddEditActivity ？那么FloatingActionButton 真正的点击事件在那里？

**Comment by zyascend** [comment]
你好，刚才检查过了，FloatingActionButton的点击事件就是在那儿，没有别的地方，通过查找它的useages也可以得出这个结论，它没有在别的地方执行逻辑。至于为什么会出现你的问题，可能是由于你在删除代码之后没有进行clean project导致的，你可以试一下clean 然后 rebuild project。最后，谢谢你提出的issue

**Comment by zyascend** [comment]
你好，刚才检查过了，FloatingActionButton的点击事件就是在那儿，没有别的地方，通过查找它的useages也可以得出这个结论，它没有在别的地方执行逻辑。至于为什么会出现你的问题，可能是由于你在删除代码之后没有进行clean project导致的，你可以试一下clean 然后 rebuild project。最后，谢谢你提出的issue

**Comment by xiechuanyu** [comment]
thank you. 的确是我没有clean导致的。。。这是android studio的bug吧。。。
